name: academy_2_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.5+20

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  vector_graphics: ^1.1.19
  vector_graphics_compiler: ^1.1.19
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^7.0.1
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.4
  file_picker: ^10.3.8
  video_player: ^2.10.1
  video_thumbnail: ^0.5.6
  isar_plus: ^1.2.0
  isar_plus_flutter_libs: ^1.2.0
  path_provider: ^2.1.5
  wakelock_plus: ^1.4.0
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  youtube_player_flutter: ^9.1.3
  http: ^1.6.0
  flutter_pdfview: ^1.4.3
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.4
  change_app_package_name: ^1.5.0
  downloadsfolder: ^1.2.0
  share_plus: ^10.0.2
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.10.4

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#F2F7FD"

flutter:

  generate: true
  
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
